name = "dobe-scan"
main = "src/index.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "auto-trailing-slash"

[[kv_namespaces]]
binding = "SMART_CACHE"
id = "c257b1bd4c48463c977f29c04633b606"

[vars]
# VAPID keys are set as Secrets in Cloudflare Dashboard:
# VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY
